### ISSUE TITLE
Not useable in Angular 11

### ISSUE THREAD

**Issue by nelnico** [TinkoffCreditSystems/angular-contenteditable-accessor#7]
When adding this to my project as per instructions, the CLI complains:

```node_modules/@tinkoff/angular-contenteditable-accessor/lib/module.d.ts:1:22 - error NG6003: Appears in the NgModule.exports of SharedModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.```

```This likely means that the library (@tinkoff/angular-contenteditable-accessor/lib/module) which declares ContenteditableValueAccessorModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also 
consider checking with the library's authors to see if the library is expected to be compatible with Ivy.```

**Comment by waterplea** [comment]
Hello @nelnico 

I just tried it on my Angular 11 project and it works fine. Try removing and reinstalling it again. Looks like `ngcc` have not processed it.
